[package]
edition = "2021"
name = "state"
version = "0.1.0"

[dependencies]
defmt = "0.3.4"
hash32 = "0.2.1"
heapless = { version = "0.7", features = ["cas", "defmt-impl"] }
seq = { git = "https://github.com/dobrite/seq.git" }
